"""add daily_actions table

Revision ID: d9a8b7c6e5f4
Revises: 2b865b2b30ba
Create Date: 2026-08-14 03:37:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd9a8b7c6e5f4'
down_revision: str | None = '2b865b2b30ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('is_completed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_actions_user_id'), 'daily_actions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_actions_user_id'), table_name='daily_actions')
    op.drop_table('daily_actions')
    # ### end Alembic commands ###